# Assignment: Weeks 7 & 8 Exercises
# Class: DSC 540
# Name: Wittlieff, Harlan
# Date: 2/6/2022

# Chapter 7

In [154]:
# Load libraries
import pandas as pd
import numpy as np

In [155]:
# Load the datafile
candy_df = pd.read_excel(r'Data/candyhierarchy2017.xlsx')

# Validate the dataload
candy_df.head()

C:\Users\wittl\anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
0,90258773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,NaN,Bottom line is Twix is really the only candy w...,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(84, 25)"
2,90272829,NaN,Male,49,USA,Virginia,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,90272840,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,...,NaN,Raisins can go to hell,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(75, 23)"
4,90272841,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 10)"

In [156]:
# Obtain the shape of the dataset
candy_df.shape

(2460, 120)

## Filter out missing data

In [157]:
# Obtain the NA counts by column
nacounts = candy_df.isna().sum()

# Sort & display the top 10 nacounts
nacounts.sort_values(ascending=False).head(10)

Unnamed: 113                 2451
Q12: MEDIA [Yahoo]           2393
Q12: MEDIA [Daily Dish]      2375
Q12: MEDIA [ESPN]            2361
Q9: OTHER COMMENTS           2074
Q8: DESPAIR OTHER            1743
Q7: JOY OTHER                1549
Q12: MEDIA [Science]         1098
Q6 | JoyJoy (Mit Iodine!)    1026
Q6 | Maynards                1024
dtype: int64

In [158]:
# The "Unnamed: 113" column is only populated in 9 rows. This column will be removed from the dataset.
candy_df = candy_df.drop(['Unnamed: 113'], axis=1)

In [159]:
# There are multiple incomplete surveys in the dataset. Drop surveys that contain more than 25% blank values.
candy_df = candy_df.dropna(thresh=30)

In [160]:
# View the shape of our filtered dataframe
candy_df.shape

(1793, 119)

## Fill in missing data

In [161]:
# Missing data in the Q12 fields will be replaced with 0 as this is a binary field
candy_df["Q12: MEDIA [Daily Dish]"] = candy_df["Q12: MEDIA [Daily Dish]"].fillna(0)
candy_df["Q12: MEDIA [Science]"] = candy_df["Q12: MEDIA [Science]"].fillna(0)
candy_df["Q12: MEDIA [ESPN]"] = candy_df["Q12: MEDIA [ESPN]"].fillna(0)
candy_df["Q12: MEDIA [Yahoo]"] = candy_df["Q12: MEDIA [Yahoo]"].fillna(0)

In [162]:
# Obtain a list of column names that excludes Q7, Q8, & Q9 as these are manual other fields that we do not want to fill NAs on.
columns = list(candy_df.columns)
unwanted = ['Q9: OTHER COMMENTS', 'Q8: DESPAIR OTHER', 'Q7: JOY OTHER']
for element in unwanted:
    columns.remove(element)
    
columns

['Internal ID',
 'Q1: GOING OUT?',
 'Q2: GENDER',
 'Q3: AGE',
 'Q4: COUNTRY',
 'Q5: STATE, PROVINCE, COUNTY, ETC',
 'Q6 | 100 Grand Bar',
 'Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes)',
 'Q6 | Any full-sized candy bar',
 'Q6 | Black Jacks',
 'Q6 | Bonkers (the candy)',
 'Q6 | Bonkers (the board game)',
 'Q6 | Bottle Caps',
 "Q6 | Box'o'Raisins",
 'Q6 | Broken glow stick',
 'Q6 | Butterfinger',
 'Q6 | Cadbury Creme Eggs',
 'Q6 | Candy Corn',
 'Q6 | Candy that is clearly just the stuff given out for free at restaurants',
 'Q6 | Caramellos',
 'Q6 | Cash, or other forms of legal tender',
 'Q6 | Chardonnay',
 'Q6 | Chick-o-Sticks (we don’t know what that is)',
 'Q6 | Chiclets',
 'Q6 | Coffee Crisp',
 'Q6 | Creepy Religious comics/Chick Tracts',
 'Q6 | Dental paraphenalia',
 'Q6 | Dots',
 'Q6 | Dove Bars',
 'Q6 | Fuzzy Peaches',
 'Q6 | Generic Brand Acetaminophen',
 'Q6 | Glow sticks',
 'Q6 | Goo Goo Clusters',
 "Q6 | Good N' Plenty",
 'Q6 | Gum from baseball cards',
 'Q6 | Gummy Bears straight up',
 'Q6 | Hard Candy',
 'Q6 | Healthy Fruit',
 'Q6 | Heath Bar',
 "Q6 | Hershey's Dark Chocolate",
 'Q6 | Hershey’s Milk Chocolate',
 "Q6 | Hershey's Kisses",
 'Q6 | Hugs (actual physical hugs)',
 'Q6 | Jolly Rancher (bad flavor)',
 'Q6 | Jolly Ranchers (good flavor)',
 'Q6 | JoyJoy (Mit Iodine!)',
 'Q6 | Junior Mints',
 'Q6 | Senior Mints',
 'Q6 | Kale smoothie',
 'Q6 | Kinder Happy Hippo',
 'Q6 | Kit Kat',
 'Q6 | LaffyTaffy',
 'Q6 | LemonHeads',
 'Q6 | Licorice (not black)',
 'Q6 | Licorice (yes black)',
 'Q6 | Lindt Truffle',
 'Q6 | Lollipops',
 'Q6 | Mars',
 'Q6 | Maynards',
 'Q6 | Mike and Ike',
 'Q6 | Milk Duds',
 'Q6 | Milky Way',
 'Q6 | Regular M&Ms',
 'Q6 | Peanut M&M’s',
 "Q6 | Blue M&M's",
 "Q6 | Red M&M's",
 "Q6 | Green Party M&M's",
 "Q6 | Independent M&M's",
 "Q6 | Abstained from M&M'ing.",
 'Q6 | Minibags of chips',
 'Q6 | Mint Kisses',
 'Q6 | Mint Juleps',
 'Q6 | Mr. Goodbar',
 'Q6 | Necco Wafers',
 'Q6 | Nerds',
 'Q6 | Nestle Crunch',
 "Q6 | Now'n'Laters",
 'Q6 | Peeps',
 'Q6 | Pencils',
 'Q6 | Pixy Stix',
 'Q6 | Real Housewives of Orange County Season 9 Blue-Ray',
 'Q6 | Reese’s Peanut Butter Cups',
 "Q6 | Reese's Pieces",
 'Q6 | Reggie Jackson Bar',
 'Q6 | Rolos',
 'Q6 | Sandwich-sized bags filled with BooBerry Crunch',
 'Q6 | Skittles',
 'Q6 | Smarties (American)',
 'Q6 | Smarties (Commonwealth)',
 'Q6 | Snickers',
 'Q6 | Sourpatch Kids (i.e. abominations of nature)',
 'Q6 | Spotted Dick',
 'Q6 | Starburst',
 'Q6 | Sweet Tarts',
 'Q6 | Swedish Fish',
 'Q6 | Sweetums (a friend to diabetes)',
 'Q6 | Take 5',
 'Q6 | Tic Tacs',
 'Q6 | Those odd marshmallow circus peanut things',
 'Q6 | Three Musketeers',
 'Q6 | Tolberone something or other',
 'Q6 | Trail Mix',
 'Q6 | Twix',
 'Q6 | Vials of pure high fructose corn syrup, for main-lining into your vein',
 'Q6 | Vicodin',
 'Q6 | Whatchamacallit Bars',
 'Q6 | White Bread',
 'Q6 | Whole Wheat anything',
 'Q6 | York Peppermint Patties',
 'Q10: DRESS',
 'Q11: DAY',
 'Q12: MEDIA [Daily Dish]',
 'Q12: MEDIA [Science]',
 'Q12: MEDIA [ESPN]',
 'Q12: MEDIA [Yahoo]',
 'Click Coordinates (x, y)']

In [163]:
# Fill the na values from the columns specified in the previous step
candy_df[columns] = candy_df[columns].fillna(method='ffill')

# Chapter 8

## Create hierarchial index

In [164]:
# Use set index to create the hierarchial index
hier_candy_df = candy_df.set_index(['Q1: GOING OUT?', 'Q2: GENDER', 'Internal ID'])

# View the dataframe
hier_candy_df

                                      Q3: AGE Q4: COUNTRY  \
Q1: GOING OUT? Q2: GENDER Internal ID
No             Male       90272821         44        USA
                          90272840         40          us
                          90272841         23         usa
                          90272852         23         usa
                          90272854         33      canada
...                                       ...         ...
               Female     90314022         26         USA
               Male       90314359         24         USA
               Female     90314580         33         USA
                          90314634         26        USA
                          90314802         66         usa

                                      Q5: STATE, PROVINCE, COUNTY, ETC  \
Q1: GOING OUT? Q2: GENDER Internal ID
No             Male       90272821                                  NM
                          90272840                                  or
                          90272841                            exton pa
                          90272852                            exton pa
                          90272854                             ontario
...                                                                ...
               Female     90314022                            Michigan
               Male       90314359                                  MD
               Female     90314580                            New York
                          90314634                           Tennessee
                          90314802                        Pennsylvania

                                      Q6 | 100 Grand Bar  \
Q1: GOING OUT? Q2: GENDER Internal ID
No             Male       90272821                   MEH
                          90272840                   MEH
                          90272841                   JOY
                          90272852                   JOY
                          90272854                   JOY
...                                                  ...
               Female     90314022                   JOY
               Male       90314359                   JOY
               Female     90314580                   MEH
                          90314634                   MEH
                          90314802               DESPAIR

                                      Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes)  \
Q1: GOING OUT? Q2: GENDER Internal ID
No             Male       90272821                                               DESPAIR
                          90272840                                               DESPAIR
                          90272841                                               DESPAIR
                          90272852                                               DESPAIR
                          90272854                                               DESPAIR
...                                                                                  ...
               Female     90314022                                                   MEH
               Male       90314359                                               DESPAIR
               Female     90314580                                               DESPAIR
                          90314634                                               DESPAIR
                          90314802                                               DESPAIR

                                      Q6 | Any full-sized candy bar  \
Q1: GOING OUT? Q2: GENDER Internal ID
No             Male       90272821                              JOY
                          90272840                              JOY
                          90272841                              JOY
                          90272852                              JOY
                          90272854                              JOY
...                                                             ...
               Female     90314022                              JOY
               Male       90314359                              MEH
               Female     90314580                              JOY
                          90314634                              JOY
                          90314802                              JOY

                                      Q6 | Black Jacks  \
Q1: GOING OUT? Q2: GENDER Internal ID
No             Male       90272821                 MEH
                          90272840                 MEH
                          90272841             DESPAIR
                          90272852             DESPAIR
                          90272854             DESPAIR
...                                                ...
               Female     90314022             DESPAIR
               Male       90314359             DESPAIR
               Female     90314580             DESPAIR
                          90314634             DESPAIR
                          90314802             DESPAIR

                                      Q6 | Bonkers (the candy)  \
Q1: GOING OUT? Q2: GENDER Internal ID
No             Male       90272821                     DESPAIR
                          90272840                         MEH
                          90272841                         MEH
                          90272852                         MEH
                          90272854                     DESPAIR
...                                                        ...
               Female     90314022                         MEH
               Male       90314359                     DESPAIR
               Female     90314580                     DESPAIR
                          90314634                         MEH
                          90314802                     DESPAIR

                                      Q6 | Bonkers (the board game)  \
Q1: GOING OUT? Q2: GENDER Internal ID
No             Male       90272821                          DESPAIR
                          90272840                          DESPAIR
                          90272841                          DESPAIR
                          90272852                          DESPAIR
                          90272854                              MEH
...                                                             ...
               Female     90314022                              MEH
               Male       90314359                              MEH
               Female     90314580                              MEH
                          90314634                              JOY
                          90314802                          DESPAIR

                                      Q6 | Bottle Caps  ...  \
Q1: GOING OUT? Q2: GENDER Internal ID                   ...
No             Male       90272821             DESPAIR  ...
                          90272840                 MEH  ...
                          90272841                 MEH  ...
                          90272852                 MEH  ...
                          90272854                 JOY  ...
...                                                ...  ...
               Female     90314022                 MEH  ...
               Male       90314359                 MEH  ...
               Female     90314580                 MEH  ...
                          90314634             DESPAIR  ...
                          90314802             DESPAIR  ...

                                                                           Q7: JOY OTHER  \
Q1: GOING OUT? Q2: GENDER Internal ID
No             Male       90272821                                                Mounds
                          90272840     Reese's crispy crunchy bars, 5th avenue bars, ...
                          90272841                                                   NaN
                          90272852                                                   NaN
                          90272854     using my elbows to get in front of the little ...
...                                                                                  ...
               Female     90314022                                                   NaN
               Male       90314359                                                Mounds
               Female     90314580                                                   NaN
                          90314634     Tiny bottles of maple syrup as given out by Cr...
                          90314802                                                   NaN

                                                                       Q8: DESPAIR OTHER  \
Q1: GOING OUT? Q2: GENDER Internal ID
No             Male       90272821                                                   NaN
                          90272840                                                   NaN
                          90272841                                                   NaN
                          90272852                                                   NaN
                          90272854     when the little kids get the big chocolate bar...
...                                                                                  ...
               Female     90314022                                                   NaN
               Male       90314359                                      Fruit Stripe Gum
               Female     90314580                                                Capers
                          90314634                                                   NaN
                          90314802                                                   NaN

                                                                      Q9: OTHER COMMENTS  \
Q1: GOING OUT? Q2: GENDER Internal ID
No             Male       90272821     Bottom line is Twix is really the only candy w...
                          90272840                                Raisins can go to hell
                          90272841                                                   NaN
                          90272852                                                   NaN
                          90272854           first person to give out cans of beer, wins
...                                                                                  ...
               Female     90314022                                                   NaN
               Male       90314359                                                   NaN
               Female     90314580                                                   NaN
                          90314634                                                   NaN
                          90314802     You hit all my chocolate highlights, and broug...

                                           Q10: DRESS Q11: DAY  \
Q1: GOING OUT? Q2: GENDER Internal ID
No             Male       90272821     White and gold   Sunday
                          90272840     White and gold   Sunday
                          90272841     White and gold   Friday
                          90272852     White and gold   Friday
                          90272854     Blue and black   Friday
...                                               ...      ...
               Female     90314022     White and gold   Friday
               Male       90314359     White and gold   Friday
               Female     90314580     Blue and black   Friday
                          90314634     Blue and black   Friday
                          90314802     White and gold   Sunday

                                      Q12: MEDIA [Daily Dish]  \
Q1: GOING OUT? Q2: GENDER Internal ID
No             Male       90272821                        0.0
                          90272840                        0.0
                          90272841                        0.0
                          90272852                        0.0
                          90272854                        0.0
...                                                       ...
               Female     90314022                        0.0
               Male       90314359                        0.0
               Female     90314580                        0.0
                          90314634                        0.0
                          90314802                        1.0

                                      Q12: MEDIA [Science] Q12: MEDIA [ESPN]  \
Q1: GOING OUT? Q2: GENDER Internal ID
No             Male       90272821                     1.0               0.0
                          90272840                     1.0               0.0
                          90272841                     1.0               0.0
                          90272852                     1.0               0.0
                          90272854                     1.0               0.0
...                                                    ...               ...
               Female     90314022                     1.0               0.0
               Male       90314359                     0.0               0.0
               Female     90314580                     1.0               0.0
                          90314634                     1.0               0.0
                          90314802                     0.0               0.0

                                      Q12: MEDIA [Yahoo]  \
Q1: GOING OUT? Q2: GENDER Internal ID
No             Male       90272821                   0.0
                          90272840                   0.0
                          90272841                   0.0
                          90272852                   0.0
                          90272854                   0.0
...                                                  ...
               Female     90314022                   0.0
               Male       90314359                   0.0
               Female     90314580                   0.0
                          90314634                   0.0
                          90314802                   0.0

                                      Click Coordinates (x, y)
Q1: GOING OUT? Q2: GENDER Internal ID
No             Male       90272821                    (84, 25)
                          90272840                    (75, 23)
                          90272841                    (70, 10)
                          90272852                    (75, 23)
                          90272854                     (55, 5)
...                                                        ...
               Female     90314022                    (68, 39)
               Male       90314359                    (68, 39)
               Female     90314580                    (70, 26)
                          90314634                    (67, 35)
                          90314802                    (19, 26)

[1793 rows x 116 columns]

## Combine and Merge Datasets

In [165]:
# Create a database for demographics
candy_demo_df = candy_df.iloc[:,:6]

# Drop Q1
candy_demo_df = candy_demo_df.drop(['Q1: GOING OUT?'], axis=1)

# View the dataframe
candy_demo_df

,Internal ID,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC"
1,90272821,Male,44,USA,NM
3,90272840,Male,40,us,or
4,90272841,Male,23,usa,exton pa
5,90272852,Male,23,usa,exton pa
7,90272854,Male,33,canada,ontario
...,...,...,...,...,...
2454,90314022,Female,26,USA,Michigan
2455,90314359,Male,24,USA,MD
2456,90314580,Female,33,USA,New York
2457,90314634,Female,26,USA,Tennessee
2459,90314802,Female,66,usa,Pennsylvania

In [166]:
# Create a database for responses
candy_resp_df = candy_df.drop(['Q2: GENDER', 'Q3: AGE', 'Q4: COUNTRY', 'Q5: STATE, PROVINCE, COUNTY, ETC'], axis=1)

# View the dataframe
candy_resp_df

,Internal ID,Q1: GOING OUT?,Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,Q6 | Bonkers (the candy),Q6 | Bonkers (the board game),Q6 | Bottle Caps,Q6 | Box'o'Raisins,...,Q7: JOY OTHER,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
1,90272821,No,MEH,DESPAIR,JOY,MEH,DESPAIR,DESPAIR,DESPAIR,DESPAIR,...,Mounds,NaN,Bottom line is Twix is really the only candy w...,White and gold,Sunday,0.0,1.0,0.0,0.0,"(84, 25)"
3,90272840,No,MEH,DESPAIR,JOY,MEH,MEH,DESPAIR,MEH,DESPAIR,...,"Reese's crispy crunchy bars, 5th avenue bars, ...",NaN,Raisins can go to hell,White and gold,Sunday,0.0,1.0,0.0,0.0,"(75, 23)"
4,90272841,No,JOY,DESPAIR,JOY,DESPAIR,MEH,DESPAIR,MEH,DESPAIR,...,NaN,NaN,NaN,White and gold,Friday,0.0,1.0,0.0,0.0,"(70, 10)"
5,90272852,No,JOY,DESPAIR,JOY,DESPAIR,MEH,DESPAIR,MEH,MEH,...,NaN,NaN,NaN,White and gold,Friday,0.0,1.0,0.0,0.0,"(75, 23)"
7,90272854,No,JOY,DESPAIR,JOY,DESPAIR,DESPAIR,MEH,JOY,MEH,...,using my elbows to get in front of the little ...,when the little kids get the big chocolate bar...,"first person to give out cans of beer, wins",Blue and black,Friday,0.0,1.0,0.0,0.0,"(55, 5)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2454,90314022,No,JOY,MEH,JOY,DESPAIR,MEH,MEH,MEH,MEH,...,NaN,NaN,NaN,White and gold,Friday,0.0,1.0,0.0,0.0,"(68, 39)"
2455,90314359,No,JOY,DESPAIR,MEH,DESPAIR,DESPAIR,MEH,MEH,DESPAIR,...,Mounds,Fruit Stripe Gum,NaN,White and gold,Friday,0.0,0.0,0.0,0.0,"(68, 39)"
2456,90314580,No,MEH,DESPAIR,JOY,DESPAIR,DESPAIR,MEH,MEH,DESPAIR,...,NaN,Capers,NaN,Blue and black,Friday,0.0,1.0,0.0,0.0,"(70, 26)"
2457,90314634,No,MEH,DESPAIR,JOY,DESPAIR,MEH,JOY,DESPAIR,MEH,...,Tiny bottles of maple syrup as given out by Cr...,NaN,NaN,Blue and black,Friday,0.0,1.0,0.0,0.0,"(67, 35)"
2459,90314802,No,DESPAIR,DESPAIR,JOY,DESPAIR,DESPAIR,DESPAIR,DESPAIR,MEH,...,NaN,NaN,"You hit all my chocolate highlights, and broug...",White and gold,Sunday,1.0,0.0,0.0,0.0,"(19, 26)"

In [167]:
# Merge the dataframes
pd.merge(candy_demo_df, candy_resp_df, on='Internal ID')

,Internal ID,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q1: GOING OUT?,Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q7: JOY OTHER,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
0,90272821,Male,44,USA,NM,No,MEH,DESPAIR,JOY,MEH,...,Mounds,NaN,Bottom line is Twix is really the only candy w...,White and gold,Sunday,0.0,1.0,0.0,0.0,"(84, 25)"
1,90272840,Male,40,us,or,No,MEH,DESPAIR,JOY,MEH,...,"Reese's crispy crunchy bars, 5th avenue bars, ...",NaN,Raisins can go to hell,White and gold,Sunday,0.0,1.0,0.0,0.0,"(75, 23)"
2,90272841,Male,23,usa,exton pa,No,JOY,DESPAIR,JOY,DESPAIR,...,NaN,NaN,NaN,White and gold,Friday,0.0,1.0,0.0,0.0,"(70, 10)"
3,90272852,Male,23,usa,exton pa,No,JOY,DESPAIR,JOY,DESPAIR,...,NaN,NaN,NaN,White and gold,Friday,0.0,1.0,0.0,0.0,"(75, 23)"
4,90272854,Male,33,canada,ontario,No,JOY,DESPAIR,JOY,DESPAIR,...,using my elbows to get in front of the little ...,when the little kids get the big chocolate bar...,"first person to give out cans of beer, wins",Blue and black,Friday,0.0,1.0,0.0,0.0,"(55, 5)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1788,90314022,Female,26,USA,Michigan,No,JOY,MEH,JOY,DESPAIR,...,NaN,NaN,NaN,White and gold,Friday,0.0,1.0,0.0,0.0,"(68, 39)"
1789,90314359,Male,24,USA,MD,No,JOY,DESPAIR,MEH,DESPAIR,...,Mounds,Fruit Stripe Gum,NaN,White and gold,Friday,0.0,0.0,0.0,0.0,"(68, 39)"
1790,90314580,Female,33,USA,New York,No,MEH,DESPAIR,JOY,DESPAIR,...,NaN,Capers,NaN,Blue and black,Friday,0.0,1.0,0.0,0.0,"(70, 26)"
1791,90314634,Female,26,USA,Tennessee,No,MEH,DESPAIR,JOY,DESPAIR,...,Tiny bottles of maple syrup as given out by Cr...,NaN,NaN,Blue and black,Friday,0.0,1.0,0.0,0.0,"(67, 35)"
1792,90314802,Female,66,usa,Pennsylvania,No,DESPAIR,DESPAIR,JOY,DESPAIR,...,NaN,NaN,"You hit all my chocolate highlights, and broug...",White and gold,Sunday,1.0,0.0,0.0,0.0,"(19, 26)"

# Chapter 10

## Grouping with Index Levels

In [168]:
# Get counts of responses by gender
hier_candy_df.groupby(level='Q2: GENDER', axis=0).count()

,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,Q6 | Bonkers (the candy),Q6 | Bonkers (the board game),Q6 | Bottle Caps,...,Q7: JOY OTHER,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
Q2: GENDER,,,,,,,,,,,,,,,,,,,,,
Female,617,617,617,617,617,617,617,617,617,617,...,343,272,139,617,617,617,617,617,617,617
I'd rather not say,60,60,60,60,60,60,60,60,60,60,...,37,28,26,60,60,60,60,60,60,60
Male,1089,1089,1089,1089,1089,1089,1089,1089,1089,1089,...,512,399,209,1089,1089,1089,1089,1089,1089,1089
Other,27,27,27,27,27,27,27,27,27,27,...,18,17,10,27,27,27,27,27,27,27

## Split/Apply/Combine

In [169]:
# Define a function to obtain the 5 youngest records
def oldest(df, n=5, column='Q3: AGE'):
    return df.sort_values(by=column)[:n]

# Replace any strings in the Age column with NAN
candy_df['Q3: AGE'] = candy_df['Q3: AGE'].apply(pd.to_numeric,errors='coerce')

# Apply the function after grouping by gender
candy_df.groupby('Q2: GENDER').apply(oldest)

                         Internal ID Q1: GOING OUT?          Q2: GENDER  \
Q2: GENDER
Female             414      90273934            Yes              Female
                   1308     90278444            Yes              Female
                   415      90273938            Yes              Female
                   433      90273991            Yes              Female
                   343      90273687            Yes              Female
I'd rather not say 954      90276766             No  I'd rather not say
                   612      90275178             No  I'd rather not say
                   1386     90278953            Yes  I'd rather not say
                   183      90273278            Yes  I'd rather not say
                   1291     90278376             No  I'd rather not say
Male               2294     90291602            Yes                Male
                   1371     90278873            Yes                Male
                   943      90276709            Yes                Male
                   1479     90279571             No                Male
                   1054     90277137            Yes                Male
Other              841      90276284            Yes               Other
                   1444     90279300             No               Other
                   1193     90277590             No               Other
                   1192     90277589             No               Other
                   1124     90277343             No               Other

                         Q3: AGE      Q4: COUNTRY  \
Q2: GENDER
Female             414       6.0    United States
                   1308      8.0              USA
                   415      10.0           Canada
                   433      10.0           Europe
                   343      11.0  North Carolina
I'd rather not say 954      12.0         New York
                   612      12.0         cascadia
                   1386     14.0             USA
                   183      18.0          america
                   1291     25.0              Usa
Male               2294      4.0              USA
                   1371      7.0           CANADA
                   943       8.0    United States
                   1479      9.0              USA
                   1054      9.0           Canada
Other              841      10.0               US
                   1444     17.0           Canada
                   1193     17.0          Iceland
                   1192     17.0          Iceland
                   1124     20.0              USA

                          Q5: STATE, PROVINCE, COUNTY, ETC Q6 | 100 Grand Bar  \
Q2: GENDER
Female             414                            Colorado                MEH
                   1308                                 TX                JOY
                   415                             Alberta                MEH
                   433                             America            DESPAIR
                   343                                USA             DESPAIR
I'd rather not say 954                              Queens                JOY
                   612                            cascadia                JOY
                   1386                        California                 JOY
                   183                                  va                JOY
                   1291                                 Ca                MEH
Male               2294                               Ohio            DESPAIR
                   1371                            ONTARIO                MEH
                   943                              Oregon                MEH
                   1479                          Kentucky                 MEH
                   1054                   British Columbia                JOY
Other              841                             Indiana            DESPAIR
                   1444           British Columbia, Canada                JOY
                   1193  Glendora, Los Angeles, California                MEH
                   1192  Glendora, Los Angeles, California                MEH
                   1124            King County, Washington                JOY

                        Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes)  \
Q2: GENDER
Female             414                                             DESPAIR
                   1308                                                MEH
                   415                                                 MEH
                   433                                                 MEH
                   343                                             DESPAIR
I'd rather not say 954                                             DESPAIR
                   612                                             DESPAIR
                   1386                                            DESPAIR
                   183                                             DESPAIR
                   1291                                            DESPAIR
Male               2294                                            DESPAIR
                   1371                                                MEH
                   943                                             DESPAIR
                   1479                                                JOY
                   1054                                                MEH
Other              841                                             DESPAIR
                   1444                                                MEH
                   1193                                            DESPAIR
                   1192                                            DESPAIR
                   1124                                            DESPAIR

                        Q6 | Any full-sized candy bar Q6 | Black Jacks  ...  \
Q2: GENDER                                                              ...
Female             414                            JOY          DESPAIR  ...
                   1308                           JOY              MEH  ...
                   415                            JOY              MEH  ...
                   433                            JOY              MEH  ...
                   343                            JOY              MEH  ...
I'd rather not say 954                            JOY          DESPAIR  ...
                   612                            JOY              MEH  ...
                   1386                           JOY          DESPAIR  ...
                   183                            JOY          DESPAIR  ...
                   1291                           JOY          DESPAIR  ...
Male               2294                           MEH          DESPAIR  ...
                   1371                           MEH          DESPAIR  ...
                   943                            JOY              MEH  ...
                   1479                           JOY          DESPAIR  ...
                   1054                           JOY              MEH  ...
Other              841                        DESPAIR          DESPAIR  ...
                   1444                           JOY              MEH  ...
                   1193                           MEH              MEH  ...
                   1192                           JOY              MEH  ...
                   1124                           MEH          DESPAIR  ...

                                                             Q7: JOY OTHER  \
Q2: GENDER
Female             414                                     Powerpuff girls
                   1308                                      Marshmallows
                   415                                                 NaN
                   433                                        Sugar Daddys
                   343                                                 NaN
I'd rather not say 954                                                 NaN
                   612                                                 NaN
                   1386  The sweet release of death The Holy Emo Trinit...
                   183                                        nothing else
                   1291                             Bubble gum, Clark bars
Male               2294                                                NaN
                   1371  Cherry Blossom (do they still make those?), in...
                   943                              Chocolate expect heath
                   1479                                        Jawbreakers
                   1054                                        this survey
Other              841                                         Comic books
                   1444                                                NaN
                   1193  bubble gum eye balls. jelly beans. chocolate b...
                   1192                                                NaN
                   1124          Any Chocolate Candy without Peanut Butter

                                                         Q8: DESPAIR OTHER  \
Q2: GENDER
Female             414                                        crunchy frog
                   1308                               Any minty chocolate
                   415                                                 NaN
                   433                                      Caramel Onions
                   343                                         Toothbrush
I'd rather not say 954                                                 NaN
                   612                                                 NaN
                   1386                                              Trump
                   183                                        nothing else
                   1291                                           Red hots
Male               2294                                                NaN
                   1371                             Loose peanuts in shell
                   943                                             Drug's
                   1479                                         Toothbrush
                   1054                                                NaN
Other              841                                          Bible shit
                   1444                                                NaN
                   1193  cadbury creme eggs should only be for easter. ...
                   1192                                                NaN
                   1124                       Any candy with Peanut Butter

                                                        Q9: OTHER COMMENTS  \
Q2: GENDER
Female             414                                                 NaN
                   1308                                                NaN
                   415                                                 NaN
                   433                                                 NaN
                   343                                                 NaN
I'd rather not say 954                                                 NaN
                   612                                                 NaN
                   1386  Since it says “mars” and not specifically a ma...
                   183   YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...
                   1291                                                NaN
Male               2294                                                NaN
                   1371                                                NaN
                   943                                                 NaN
                   1479                                                NaN
                   1054                                                NaN
Other              841                                                 NaN
                   1444                                                NaN
                   1193                                 no rockets listed?
                   1192                                                NaN
                   1124                                                NaN

                             Q10: DRESS Q11: DAY Q12: MEDIA [Daily Dish]  \
Q2: GENDER
Female             414   White and gold   Friday                     0.0
                   1308  Blue and black   Friday                     0.0
                   415   White and gold   Sunday                     0.0
                   433   Blue and black   Friday                     0.0
                   343   White and gold   Friday                     1.0
I'd rather not say 954   Blue and black   Friday                     0.0
                   612   White and gold   Friday                     0.0
                   1386  Blue and black   Friday                     0.0
                   183   White and gold   Friday                     0.0
                   1291  Blue and black   Sunday                     0.0
Male               2294  Blue and black   Friday                     0.0
                   1371  White and gold   Sunday                     0.0
                   943   Blue and black   Friday                     1.0
                   1479  White and gold   Sunday                     0.0
                   1054  White and gold   Sunday                     0.0
Other              841   Blue and black   Friday                     0.0
                   1444  White and gold   Friday                     0.0
                   1193  Blue and black   Friday                     0.0
                   1192  White and gold   Sunday                     0.0
                   1124  Blue and black   Sunday                     0.0

                        Q12: MEDIA [Science] Q12: MEDIA [ESPN]  \
Q2: GENDER
Female             414                   1.0               0.0
                   1308                  1.0               0.0
                   415                   1.0               0.0
                   433                   0.0               0.0
                   343                   0.0               0.0
I'd rather not say 954                   0.0               0.0
                   612                   0.0               0.0
                   1386                  1.0               0.0
                   183                   1.0               0.0
                   1291                  0.0               0.0
Male               2294                  1.0               0.0
                   1371                  1.0               0.0
                   943                   0.0               0.0
                   1479                  0.0               0.0
                   1054                  0.0               0.0
Other              841                   1.0               0.0
                   1444                  1.0               0.0
                   1193                  1.0               0.0
                   1192                  1.0               0.0
                   1124                  0.0               0.0

                        Q12: MEDIA [Yahoo] Click Coordinates (x, y)
Q2: GENDER
Female             414                 0.0                 (64, 18)
                   1308                0.0                  (58, 6)
                   415                 0.0                 (85, 21)
                   433                 0.0                 (78, 31)
                   343                 0.0                 (25, 26)
I'd rather not say 954                 0.0                 (31, 76)
                   612                 0.0                 (76, 21)
                   1386                0.0                 (82, 13)
                   183                 0.0                 (74, 42)
                   1291                0.0                 (81, 27)
Male               2294                0.0                 (77, 40)
                   1371                0.0                 (74, 11)
                   943                 0.0                 (37, 17)
                   1479                0.0                 (66, 36)
                   1054                0.0                 (71, 35)
Other              841                 0.0                  (79, 7)
                   1444                0.0                 (72, 26)
                   1193                0.0                 (76, 19)
                   1192                0.0                 (84, 36)
                   1124                1.0                 (88, 90)

[20 rows x 119 columns]

# Chapter 11

In [170]:
# Load the datafile
boing_df = pd.read_excel(r'Data/BOING-BOING-CANDY-HIERARCHY-2016-SURVEY-Responses.xlsx')

# View the dataframe
boing_df

,Timestamp,Are you going actually going trick or treating yourself?,Your gender:,How old are you?,Which country do you live in?,"Which state, province, county do you live in?",[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],...,Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling],Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams],Please estimate the degree(s) of separation you have from the following celebrities [Beyoncé],Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"Which day do you prefer, Friday or Sunday?","Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?","When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).",[York Peppermint Patties] Ignore
0,2016-10-24 05:09:23.033,No,Male,22,Canada,Ontario,JOY,DESPAIR,JOY,MEH,...,3 or higher,2,3 or higher,3 or higher,3 or higher,3 or higher,Friday,South to North,Science: Latest News and Headlines,NaN
1,2016-10-24 05:09:54.798,No,Male,45,usa,il,MEH,MEH,JOY,JOY,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
2,2016-10-24 05:13:06.734,No,Female,48,US,Colorado,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN
3,2016-10-24 05:14:17.192,No,Male,57,usa,il,JOY,MEH,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,South to North,Science: Latest News and Headlines,NaN
4,2016-10-24 05:14:24.625,Yes,Male,42,USA,South Dakota,MEH,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,ESPN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,2016-10-29 16:53:52.516,No,Female,52,USA,TX,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,2,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
1255,2016-10-30 06:53:54.735,No,Male,33,united states,minnesota,JOY,DESPAIR,JOY,DESPAIR,...,"Actually, that's me.",3 or higher,3 or higher,3 or higher,3 or higher,"Actually, that's me.",Friday,Sinusoidally around the equator,Science: Latest News and Headlines,NaN
1256,2016-10-30 11:06:10.827,No,Male,NaN,NaN,NaN,JOY,MEH,JOY,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Sunday,nne to east to nnw to s to n,Science: Latest News and Headlines,NaN
1257,2016-10-30 16:07:26.539,No,Male,48,canada,BC,NaN,DESPAIR,JOY,DESPAIR,...,1,2,3 or higher,3 or higher,2,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN
1258,2016-10-30 17:06:45.660,Yes,Female,44,Us,Nh,JOY,MEH,JOY,JOY,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Daily Dish,NaN

## Convert between string and date time

In [171]:
# Convert to string
boing_df['string time'] = boing_df['Timestamp'].astype(str)

# View the new column
boing_df['string time']

0       2016-10-24 05:09:23.033
1       2016-10-24 05:09:54.798
2       2016-10-24 05:13:06.734
3       2016-10-24 05:14:17.192
4       2016-10-24 05:14:24.625
                 ...
1254    2016-10-29 16:53:52.516
1255    2016-10-30 06:53:54.735
1256    2016-10-30 11:06:10.827
1257    2016-10-30 16:07:26.539
1258    2016-10-30 17:06:45.660
Name: string time, Length: 1259, dtype: object

In [172]:
# Convert string to time
boing_df['Time'] = pd.to_datetime(boing_df['string time'])

# View the new column
boing_df['Time']

0      2016-10-24 05:09:23.033
1      2016-10-24 05:09:54.798
2      2016-10-24 05:13:06.734
3      2016-10-24 05:14:17.192
4      2016-10-24 05:14:24.625
                 ...
1254   2016-10-29 16:53:52.516
1255   2016-10-30 06:53:54.735
1256   2016-10-30 11:06:10.827
1257   2016-10-30 16:07:26.539
1258   2016-10-30 17:06:45.660
Name: Time, Length: 1259, dtype: datetime64[ns]

## Convert timestamps to periods and back

In [173]:
# Set Timestamp as the index
boing_df = boing_df.set_index(['Timestamp'])

# Convert to periods with a daily frequency
period_df = boing_df.to_period(freq='D')
# view the dataframe
period_df

,Are you going actually going trick or treating yourself?,Your gender:,How old are you?,Which country do you live in?,"Which state, province, county do you live in?",[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],[Bonkers (the candy)],...,Please estimate the degree(s) of separation you have from the following celebrities [Beyoncé],Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"Which day do you prefer, Friday or Sunday?","Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?","When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).",[York Peppermint Patties] Ignore,string time,Time
Timestamp,,,,,,,,,,,,,,,,,,,,,
2016-10-24,No,Male,22,Canada,Ontario,JOY,DESPAIR,JOY,MEH,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,Friday,South to North,Science: Latest News and Headlines,NaN,2016-10-24 05:09:23.033,2016-10-24 05:09:23.033
2016-10-24,No,Male,45,usa,il,MEH,MEH,JOY,JOY,DESPAIR,...,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN,2016-10-24 05:09:54.798,2016-10-24 05:09:54.798
2016-10-24,No,Female,48,US,Colorado,JOY,DESPAIR,JOY,MEH,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN,2016-10-24 05:13:06.734,2016-10-24 05:13:06.734
2016-10-24,No,Male,57,usa,il,JOY,MEH,JOY,MEH,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,South to North,Science: Latest News and Headlines,NaN,2016-10-24 05:14:17.192,2016-10-24 05:14:17.192
2016-10-24,Yes,Male,42,USA,South Dakota,MEH,DESPAIR,JOY,DESPAIR,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,ESPN,NaN,2016-10-24 05:14:24.625,2016-10-24 05:14:24.625
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-10-29,No,Female,52,USA,TX,JOY,DESPAIR,JOY,MEH,MEH,...,3 or higher,3 or higher,2,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN,2016-10-29 16:53:52.516,2016-10-29 16:53:52.516
2016-10-30,No,Male,33,united states,minnesota,JOY,DESPAIR,JOY,DESPAIR,MEH,...,3 or higher,3 or higher,3 or higher,"Actually, that's me.",Friday,Sinusoidally around the equator,Science: Latest News and Headlines,NaN,2016-10-30 06:53:54.735,2016-10-30 06:53:54.735
2016-10-30,No,Male,NaN,NaN,NaN,JOY,MEH,JOY,NaN,DESPAIR,...,NaN,NaN,NaN,NaN,Sunday,nne to east to nnw to s to n,Science: Latest News and Headlines,NaN,2016-10-30 11:06:10.827,2016-10-30 11:06:10.827
2016-10-30,No,Male,48,canada,BC,NaN,DESPAIR,JOY,DESPAIR,MEH,...,3 or higher,3 or higher,2,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN,2016-10-30 16:07:26.539,2016-10-30 16:07:26.539
2016-10-30,Yes,Female,44,Us,Nh,JOY,MEH,JOY,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Daily Dish,NaN,2016-10-30 17:06:45.660,2016-10-30 17:06:45.660

In [174]:
# Convert from daily period to timestamp at end of day
ts_df = period_df.to_timestamp(how='end')

# View the dataframe
ts_df

,Are you going actually going trick or treating yourself?,Your gender:,How old are you?,Which country do you live in?,"Which state, province, county do you live in?",[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],[Bonkers (the candy)],...,Please estimate the degree(s) of separation you have from the following celebrities [Beyoncé],Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"Which day do you prefer, Friday or Sunday?","Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?","When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).",[York Peppermint Patties] Ignore,string time,Time
Timestamp,,,,,,,,,,,,,,,,,,,,,
2016-10-24 23:59:59.999999999,No,Male,22,Canada,Ontario,JOY,DESPAIR,JOY,MEH,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,Friday,South to North,Science: Latest News and Headlines,NaN,2016-10-24 05:09:23.033,2016-10-24 05:09:23.033
2016-10-24 23:59:59.999999999,No,Male,45,usa,il,MEH,MEH,JOY,JOY,DESPAIR,...,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN,2016-10-24 05:09:54.798,2016-10-24 05:09:54.798
2016-10-24 23:59:59.999999999,No,Female,48,US,Colorado,JOY,DESPAIR,JOY,MEH,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN,2016-10-24 05:13:06.734,2016-10-24 05:13:06.734
2016-10-24 23:59:59.999999999,No,Male,57,usa,il,JOY,MEH,JOY,MEH,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,South to North,Science: Latest News and Headlines,NaN,2016-10-24 05:14:17.192,2016-10-24 05:14:17.192
2016-10-24 23:59:59.999999999,Yes,Male,42,USA,South Dakota,MEH,DESPAIR,JOY,DESPAIR,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,ESPN,NaN,2016-10-24 05:14:24.625,2016-10-24 05:14:24.625
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-10-29 23:59:59.999999999,No,Female,52,USA,TX,JOY,DESPAIR,JOY,MEH,MEH,...,3 or higher,3 or higher,2,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN,2016-10-29 16:53:52.516,2016-10-29 16:53:52.516
2016-10-30 23:59:59.999999999,No,Male,33,united states,minnesota,JOY,DESPAIR,JOY,DESPAIR,MEH,...,3 or higher,3 or higher,3 or higher,"Actually, that's me.",Friday,Sinusoidally around the equator,Science: Latest News and Headlines,NaN,2016-10-30 06:53:54.735,2016-10-30 06:53:54.735
2016-10-30 23:59:59.999999999,No,Male,NaN,NaN,NaN,JOY,MEH,JOY,NaN,DESPAIR,...,NaN,NaN,NaN,NaN,Sunday,nne to east to nnw to s to n,Science: Latest News and Headlines,NaN,2016-10-30 11:06:10.827,2016-10-30 11:06:10.827
2016-10-30 23:59:59.999999999,No,Male,48,canada,BC,NaN,DESPAIR,JOY,DESPAIR,MEH,...,3 or higher,3 or higher,2,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN,2016-10-30 16:07:26.539,2016-10-30 16:07:26.539
2016-10-30 23:59:59.999999999,Yes,Female,44,Us,Nh,JOY,MEH,JOY,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Daily Dish,NaN,2016-10-30 17:06:45.660,2016-10-30 17:06:45.660